version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    #image: bitnami/mongodb:latest
    build: ./.docker/mongo
    ports:
      - 27017:27017
    volumes:
      #- mongodb_data:/bitnami/mongodb
      - mongodb_data:/data/db
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

  #db:
  #  build: ./.docker/mongo
  #  ports:
  #    - 27017:27017
  #  environment:
  #    MONGO_INITDB_ROOT_PASSWORD: root
  #    MONGO_REPLICA_HOST: db
  #  volumes:
  #    - mongodb_data:/data/db

  redis:
    image: arm64v8/redis:alpine  

volumes:
  mongodb_data:
    driver: local

#networks:
#  my-network:
#    external: true
